#!/usr/bin/env python3
"""Generate horror.html from index.html.

The two pages share all their behaviour. Rather than maintain a second copy,
this rewrites the palette, the type stacks, the scale labels and the wording,
and leaves the script untouched apart from the band labels. Run it after any
change to index.html:

    ./build-horror.py

If a substitution stops matching it is reported and the build fails, so an
edit to index.html cannot silently leave the horror cut half updated.
"""
import re
import sys
import urllib.parse

SRC, DST = "index.html", "horror.html"

# Sun-bleached one-sheet: dirty bone, oxblood, rust.
LIGHT = {
    "--paper:": "#E5DCC9", "--paper-sunk:": "#D8CDB6", "--card:": "#F1EADB",
    "--ink:": "#14100C", "--ink-mid:": "#574C3E", "--ink-faint:": "#8A7C68",
    "--chile:": "#8E1409", "--chile-deep:": "#5C0B04", "--flame:": "#B4551D",
    "--char:": "#0B0907", "--char-soft:": "#14100C", "--bone:": "#E5DCC9",
    "--rule:": "#C9BCA2", "--rule-firm:": "#A8987A", "--pip-off:": "#B6A88C",
    "--h1:": "#6E7A38", "--h2:": "#8E1409", "--h3:": "#A82F0F", "--h4:": "#BF5A16",
    "--h5:": "#CE8A22", "--h6:": "#E4CE8E", "--h6-edge:": "#9C7A22",
    "--name-color:": "#8E1409",
}
DARK = {
    "--paper:": "#0C0A08", "--paper-sunk:": "#120E0B", "--card:": "#17120E",
    "--ink:": "#E2D7C3", "--ink-mid:": "#9A8C77", "--ink-faint:": "#7A6D5C",
    "--chile:": "#C62A18", "--chile-deep:": "#E0503A", "--flame:": "#D2822F",
    "--char:": "#060504", "--char-soft:": "#100D0A", "--bone:": "#E2D7C3",
    "--rule:": "#2A211A", "--rule-firm:": "#3E3226", "--pip-off:": "#362B21",
    "--h1:": "#8A9A48", "--h2:": "#C62A18", "--h3:": "#D8451C", "--h4:": "#E4721F",
    "--h5:": "#EFA033", "--h6:": "#F2E0A8", "--h6-edge:": "#A8862E",
    "--name-color:": "#E0503A",
}

FONT_LINK = (
    '<link rel="stylesheet" href="https://fonts.googleapis.com/css2'
    "?family=Special+Elite"
    "&family=Comic+Neue:ital,wght@0,400;0,700;1,400;1,700"
    "&family=Barlow:ital,wght@0,400;0,500;0,600;1,400"
    "&family=Barlow+Condensed:wght@500;600;700"
    '&display=swap">'
)

WIRE_SVG = (
    # Traced from the wire in their logo: two strands twisted together read
    # as a chain of lenses that bulge and pinch, not a straight line. The
    # knot is a coil built from overlapping lobes offset left and right, so
    # its outline is lumpy rather than a smooth lozenge. Barbs are steep and
    # project well clear of the strand rather than splaying sideways.
    "<svg xmlns='http://www.w3.org/2000/svg' width='72' height='14'>"
    "<path fill='#000' d='M0 6.6 Q9 2.6 18 6.6 Q27 2.6 36 6.6 Q45 2.6 54 6.6"
    " Q63 2.6 72 6.6 L72 7.4 Q63 11.4 54 7.4 Q45 11.4 36 7.4 Q27 11.4 18 7.4"
    " Q9 11.4 0 7.4 Z'/>"
    "<g fill='#000'>"
    "<ellipse cx='36' cy='7' rx='3.4' ry='4'/>"
    "<circle cx='34.5' cy='3.5' r='2.1'/>"
    "<circle cx='37.7' cy='5.3' r='2.3'/>"
    "<circle cx='34.3' cy='8.8' r='2.3'/>"
    "<circle cx='37.5' cy='10.7' r='2'/>"
    "</g>"
    "<g fill='none' stroke='#000' stroke-width='1.8' stroke-linecap='round'>"
    "<path d='M34.4 5.4 L32.2 0.6'/>"
    "<path d='M37.6 5.4 L39.8 0.6'/>"
    "<path d='M34.4 8.6 L32.2 13.4'/>"
    "</g></svg>"
)

GRAIN_SVG = (
    "<svg xmlns='http://www.w3.org/2000/svg' width='260' height='260'>"
    "<filter id='n'><feTurbulence type='fractalNoise' baseFrequency='0.82' "
    "numOctaves='4' stitchTiles='stitch'/></filter>"
    "<rect width='100%' height='100%' filter='url(#n)'/></svg>"
)

OVERRIDES = """
  /* ================= horror cut =================
     Everything below is the only styling difference from index.html.
     Generated by build-horror.py, do not hand edit. */

  /* Print grain and a vignette, so the page reads like a sun-bleached
     one-sheet rather than a clean web page. Both are inert overlays. */
  body::after {
    content: ""; position: fixed; inset: 0; z-index: 60; pointer-events: none;
    background-image: url("__GRAIN__");
    background-size: 260px 260px;
    opacity: 0.30; mix-blend-mode: multiply;
  }

  body::before {
    content: ""; position: fixed; inset: 0; z-index: 59; pointer-events: none;
    background: radial-gradient(ellipse at 50% 42%, transparent 42%, rgba(6,5,4,0.42) 100%);
  }

  :root[data-theme="dark"] body::after { mix-blend-mode: screen; opacity: 0.16; }

  /* Special Elite is a light face. Give the big type some weight and air. */
  .hero h1 {
    letter-spacing: -0.005em; line-height: 1.02;
    text-shadow: 0 3px 0 rgba(0,0,0,0.30), 0 2px 26px rgba(0,0,0,0.62);
  }

  h2 { line-height: 1.06; }

  /* Typewriter for the small print, like a case file. The two maker names
     carry .eyebrow as well, but they are set like product names, so they are
     excluded here: this block sits after .maker at the same specificity and
     would otherwise win. */
  .eyebrow:not(.maker), .stub, .heat-word, .cal-when, .draft {
    font-family: "Special Elite", "Courier New", monospace;
    letter-spacing: 0.05em;
  }

  .eyebrow:not(.maker) { font-size: 14px; }
  .heat-word { font-size: 11.5px; }

  /* Squared off, heavier rules. Nothing here is soft. */
  .btn, .prod, .deal, .cal-stub, .split img, .scale-key, .filters button { border-radius: 0; }
  .prod { border-color: var(--rule-firm); }
  .prod::before { width: 4px; }

  .hero-logo {
    background: rgba(232,224,205,0.92);
    box-shadow: 0 6px 34px rgba(0,0,0,0.75);
    filter: saturate(0.88) contrast(1.05);
  }

  /* Barbed wire runs along the top band and both edges of the story block,
     picking up the wire in the logo. Masked rather than drawn in a fixed
     colour so it follows the theme. Section headings keep a plain rule: wire
     under every one of them was too much of a good thing. */
  .strip, .story { position: relative; }

  .strip::before, .strip::after,
  .story::before, .story::after {
    content: ""; position: absolute; left: 0; right: 0; height: 14px;
    background-color: var(--chile);
    opacity: 0.85;
    -webkit-mask-image: url("__WIRE__"); mask-image: url("__WIRE__");
    -webkit-mask-repeat: repeat-x; mask-repeat: repeat-x;
    -webkit-mask-size: 72px 14px; mask-size: 72px 14px;
    -webkit-mask-position: left center; mask-position: left center;
    pointer-events: none; z-index: 2;
  }

  /* The wire graphic runs through the middle of its 14px tile, so the strip
     is pulled out by half its height to put the wire itself exactly on the
     boundary rather than 7px inside it. */
  .strip::before, .story::before { top: -7px; }
  .strip::after,  .story::after  { bottom: -7px; }

  /* --- flourishes. All decorative, all aria-hidden, none affect layout. --- */

  .flourish { display: inline-block; vertical-align: middle; flex: none; }

  /* Scythe and cleaver sit at the end of a line of body copy, so they take
     their colour from it and stay legible in both themes. */
  /* A tall glyph inside a paragraph stretches the line box it lands on, which
     knocked the leading out. These sit beside the whole block instead. */
  .lede-row { display: flex; align-items: center; gap: 20px; }
  .lede-row .lede { margin-top: 0; }

  @media (max-width: 620px) {
    .lede-row { flex-direction: column; align-items: flex-start; gap: 6px; }
  }

  .flourish-blade {
    width: 84px; height: 56px;
    color: var(--chile); opacity: 0.85;
  }

  .flourish-blade .edge { fill: currentColor; }
  .flourish-blade .haft { stroke: currentColor; stroke-width: 3.6; stroke-linecap: round; fill: none; }
  .flourish-blade .grip { stroke: currentColor; stroke-width: 7; stroke-linecap: round; fill: none; }
  .flourish-blade .hole { fill: var(--paper); }

  /* The footer is dark in both themes, so the holes can be a fixed near-black
     punched through it, with a chipped rim catching the light. */
  .flourish-holes { width: 118px; height: 52px; margin-left: 18px; }

  .flourish-spatter { width: 58px; height: 24px; margin-left: 12px; color: var(--chile); }
  .flourish-spatter .drop { fill: currentColor; }
  .flourish-holes .hole { fill: #050403; }
  .flourish-holes .rim { fill: none; stroke: rgba(236,222,200,0.38); stroke-width: 1.3; }
  .flourish-holes .crack { stroke: rgba(236,222,200,0.30); stroke-width: 1.3; stroke-linecap: round; }

  .foot-top h2 { display: flex; align-items: center; flex-wrap: wrap; }

"""

SCYTHE = ('<svg class="flourish flourish-blade" viewBox="0 0 84 56" aria-hidden="true" focusable="false"><path class="edge" d="M53 8 C38 6 18 12 6 26 C20 18 38 16 52 18 Z"/><path class="haft" d="M52 12 L60 52"/><path class="haft" d="M56 34 L68 29"/></svg>')

CLEAVER = ('<svg class="flourish flourish-blade" viewBox="0 0 84 56" aria-hidden="true" focusable="false"><path class="edge" d="M8 9 H48 V37 C35 45 21 45 8 37 Z"/><circle class="hole" cx="15" cy="17" r="3"/><path class="grip" d="M52 25 H76"/></svg>')

HOLES = ('<svg class="flourish flourish-holes" viewBox="0 0 118 52" aria-hidden="true" focusable="false"><g class="crack"><path d="M22 24 L6 12"/><path d="M22 24 L38 13"/><path d="M22 24 L18 44"/><path d="M22 24 L37 37"/><path d="M63 17 L51 5"/><path d="M63 17 L77 10"/><path d="M63 17 L60 32"/><path d="M95 34 L110 26"/><path d="M95 34 L86 47"/><path d="M95 34 L106 45"/></g><circle class="hole" cx="22" cy="24" r="8.5"/><circle class="rim" cx="22" cy="24" r="10"/><circle class="hole" cx="63" cy="17" r="6"/><circle class="rim" cx="63" cy="17" r="7.4"/><circle class="hole" cx="95" cy="34" r="7"/><circle class="rim" cx="95" cy="34" r="8.5"/></svg>')

SPATTER = ('<svg class="flourish flourish-spatter" viewBox="0 0 58 24" aria-hidden="true" focusable="false"><g class="drop"><path d="M20 5 C26 2 33 4 34 9 C35 15 30 19 24 18 C17 17 13 12 15 8 C16 6 18 5 20 5 Z"/><path d="M38 6 C41 5 44 7 43 10 C42 13 38 13 37 10 C36 8 37 6 38 6 Z"/><circle cx="9" cy="4" r="2.1"/><circle cx="6" cy="14" r="1.5"/><circle cx="12" cy="20" r="1.2"/><circle cx="30" cy="21" r="1.6"/><circle cx="47" cy="16" r="2.3"/><circle cx="52" cy="7" r="1.4"/><circle cx="56" cy="19" r="1"/><circle cx="42" cy="2" r="1.1"/></g></svg>')

# (find, replace). Every one must match or the build fails.
COPY = [
    ('--display: "Alfa Slab One", Georgia, serif;',
     '--display: "Special Elite", "Courier New", monospace;'),
    ('--body:    "IBM Plex Sans", -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif;',
     '--body:    "Barlow", -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif;'),

    # the scale keeps its shape, only the words change
    ('{ key: "mild",   range: [1, 1], label: "Mild" },',
     '{ key: "mild",   range: [1, 1], label: "Harmless" },'),
    ('{ key: "medium", range: [2, 3], label: "Medium" },',
     '{ key: "medium", range: [2, 3], label: "Uneasy" },'),
    ('{ key: "hot",    range: [4, 5], label: "Hot" },',
     '{ key: "hot",    range: [4, 5], label: "Regrettable" },'),
    ('{ key: "beyond", range: [6, 6], label: "Beyond" }',
     '{ key: "beyond", range: [6, 6], label: "No survivors" }'),

    ("Draft preview. Product list, prices and heat ratings still need Paula &amp; Crazy John to confirm.",
     "Draft preview, horror cut. Product list, prices and heat ratings still need Paula &amp; Crazy John to confirm."),
    ("<h1>Home grown, <em>hand jarred, seriously hot.</em></h1>",
     "<h1>Home grown. <em>Hand jarred. No survivors.</em></h1>"),
    ("Small-batch salsa, hot sauce, cowboy candy, pickles and chow chow, made from ingredients we grow ourselves, in a kitchen that smells like it.",
     "Small-batch salsa, hot sauce, cowboy candy, pickles and chow chow. Everything grown out back, everything put up by hand, in a kitchen you would not want to walk into unannounced."),
    (">Find Our Booth<", ">Find The Booth<"),
    ("<span>Mild to ghostly and beyond</span>", "<span>Mild to unholy</span>"),
    ("<span>Lots of them</span>", "<span>More than is wise</span>"),
    ("<span>Ask at the booth</span>", "<span>Ask, if you're brave</span>"),
    ('<p class="lede">Crazy John builds these one small batch at a time, and they climb from friendly to genuinely reckless. The rating is his own, it goes past the reaper, and he does not grade on a curve.</p>',
     '<div class="lede-row"><p class="lede">Crazy John builds these one small batch at a time, out in the shed, and they climb from friendly to genuinely reckless. The rating is his own, it goes well past the reaper, and he does not grade on a curve.</p>'
     + SCYTHE + "</div>"),

    ('<p class="lede">Paula\'s side of the table. Same garden, gentler intentions. Mostly.</p>',
     '<div class="lede-row"><p class="lede">Paula\'s side of the table. Same garden, gentler intentions. Mostly.</p>'
     + CLEAVER + "</div>"),

    ("<h2>Come get some.</h2>", "<h2>Come get some." + HOLES + "</h2>"),

    ('<p class="eyebrow">What it costs</p>',
     '<p class="eyebrow">What it costs' + SPATTER + "</p>"),
    ("We're at markets and community events around Elgin and Central Texas most weekends. This list keeps itself up to date.",
     "We're at markets and community events around Elgin and Central Texas most weekends. You will know the booth when you see it."),
]


def repaint(css, table):
    for token, value in table.items():
        css = re.sub(r"(" + re.escape(token) + r"\s*)#[0-9A-Fa-f]{6}",
                     lambda m: m.group(1) + value, css)
    return css


def main():
    s = open(SRC, encoding="utf-8").read()

    s = re.sub(r'<link rel="stylesheet" href="https://fonts\.googleapis\.com/css2[^"]*">',
               FONT_LINK.replace("\\", "\\\\"), s)

    blocks = list(re.finditer(
        r'(:root \{|:root\[data-theme="dark"\] \{)(.*?)\n  \}',
        s, re.S))
    if len(blocks) != 2:
        sys.exit("FAIL: expected 2 token blocks, found %d" % len(blocks))

    out, last = [], 0
    for i, m in enumerate(blocks):
        out.append(s[last:m.start()])
        out.append(m.group(1) + repaint(m.group(2), LIGHT if i == 0 else DARK) + "\n  }")
        last = m.end()
    out.append(s[last:])
    s = "".join(out)

    missing = [a for a, _ in COPY if a not in s]
    if missing:
        sys.exit("FAIL: these no longer match index.html:\n  " + "\n  ".join(missing))
    for a, b in COPY:
        s = s.replace(a, b)

    grain = "data:image/svg+xml," + urllib.parse.quote(GRAIN_SVG, safe="")
    wire = "data:image/svg+xml," + urllib.parse.quote(WIRE_SVG, safe="")
    anchor = "  @media (prefers-reduced-motion: reduce) {"
    if anchor not in s:
        sys.exit("FAIL: could not find the reduced-motion block to insert before")
    s = s.replace(anchor,
                  OVERRIDES.replace("__GRAIN__", grain).replace("__WIRE__", wire) + "\n" + anchor, 1)

    # the type picker belongs to the other design
    s = re.sub(r'\n  <span class="draft-fonts">.*?</span>\n', "\n", s, flags=re.S)

    open(DST, "w", encoding="utf-8").write(s)
    print("wrote %s from %s" % (DST, SRC))


if __name__ == "__main__":
    main()
