/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 974e70d4f7f4cd0c1ba099cc803fd3c3)
// GlobalProps omitted: keep the entry as a plain default export for assets.
interface __BaseEnv_Env {
	CATALOG: KVNamespace;
	MAIL_IP: RateLimit;
	MAIL_EMAIL: RateLimit;
	SEND_IP: RateLimit;
	ASSETS: Fetcher;
	PRODUCTS_CSV_URL: string;
	EVENTS_CSV_URL: string;
}
interface Env extends __BaseEnv_Env {}
