/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: c98c291b892ab511eb6ffa4b44c6ff50)
// GlobalProps from that command is omitted on purpose: worker.ts also exports
// helpers for unit tests, and those named exports are not a Worker entrypoint.
interface __BaseEnv_Env {
	MAIL_IP: RateLimit;
	MAIL_EMAIL: RateLimit;
	SEND_IP: RateLimit;
	ASSETS: Fetcher;
}
interface Env extends __BaseEnv_Env {}
