/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 3bebfcabb1925d33b6d4b9f19897cfc1)
// GlobalProps from that command is omitted on purpose: worker.ts also exports
// helpers for unit tests, and those named exports are not a Worker entrypoint.
interface __BaseEnv_Env {
	MAIL_IP: RateLimit;
	MAIL_EMAIL: RateLimit;
	SEND_IP: RateLimit;
}
interface Env extends __BaseEnv_Env {}
