#!/usr/bin/env node
/* Write the product cards into both pages, so a visitor whose browser never
 * runs site.js still gets the catalog.
 *
 *     tools/make-catalog.mjs            rewrite the blocks
 *     tools/make-catalog.mjs --check    fail if they are out of date
 *
 * The cards are built by lib/render.js - the same productCard the browser
 * calls - against a DOM shim, so there is one definition of what a card is.
 * Reimplementing it here in string concatenation would work until the day the
 * two drifted, and then it would be wrong silently.
 *
 * The schedule is deliberately not baked. renderEvents drops dates before
 * today, so its output depends on when it ran, and a generated file whose
 * --check fails every morning is worse than no generated file.
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { parseHTML } from "linkedom";

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.join(here, "..");

// productCard builds detached nodes, so any document will do as a factory.
globalThis.document = parseHTML("<!doctype html><body></body>").document;

const { csvToObjects, featuredFrom, forMaker } = await import("../public/lib/data.js");
const { productCard } = await import("../public/lib/render.js");

const MAKERS = ["Paula", "John"];
const TARGETS = [
  { file: "legacy/html/index.html", featured: true },   // pre-Astro bake (step 4 deletes)
  { file: "legacy/html/products.html", featured: false },
];

const rows = csvToObjects(fs.readFileSync(path.join(root, "data/products.csv"), "utf8"));

function block(maker, featured) {
  const mine = forMaker(rows, maker.toLowerCase());
  const shown = featured ? featuredFrom(mine) : mine;
  return shown.map((p) => "      " + productCard(p).outerHTML).join("\n");
}

let stale = [];
for (const { file, featured } of TARGETS) {
  const full = path.join(root, file);
  let html = fs.readFileSync(full, "utf8");
  for (const maker of MAKERS) {
    const open = `      <!-- >>> generated by tools/make-catalog.mjs: ${maker} <<< -->`;
    const close = `      <!-- >>> end generated: ${maker} <<< -->`;
    const a = html.indexOf(open);
    const b = html.indexOf(close, a);
    if (a === -1 || b === -1) {
      console.error(`FAIL: ${file} has no ${maker} block. Expected:\n${open}\n...\n${close}`);
      process.exit(1);
    }
    const fresh = `${open}\n${block(maker, featured)}\n${close}`;
    html = html.slice(0, a) + fresh + html.slice(b + close.length);
  }
  const current = fs.readFileSync(full, "utf8");
  if (html === current) continue;
  if (process.argv.includes("--check")) stale.push(file);
  else {
    fs.writeFileSync(full, html);
    console.log(`rewrote the catalog blocks in ${file}`);
  }
}

if (process.argv.includes("--check")) {
  if (stale.length) {
    console.error(`FAIL: ${stale.join(", ")} out of date. Run tools/make-catalog.mjs`);
    process.exit(1);
  }
  console.log("catalog blocks are up to date");
}
