#!/usr/bin/env python3
"""Regenerate the procedural CSS values in index.html.

Everything this writes is a *value*: two texture tiles, four torn-print mask
outlines and four scatters of stains, all emitted as custom properties inside
one marked block. Selectors stay in the stylesheet, so renaming a class can
never silently disconnect the generated art from the page.

    tools/make-assets.py            rewrite the block in index.html
    tools/make-assets.py --check    fail if the block is out of date

Seeds are fixed, so output is byte-stable: a run with no source change is a
no-op. Tune a shape by editing the constants here and rerunning.
"""
import os
import random
import re
import sys
import urllib.parse

# Repo-relative, so the script works from anywhere.
PAGE = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "index.html")
OPEN = "  /* >>> generated by tools/make-assets.py, do not edit by hand <<< */"
CLOSE = "  /* >>> end generated <<< */"

WIRE_SVG = (
    # Traced from the wire in their logo: two strands twisted together read
    # as a chain of lenses that bulge and pinch, not a straight line. The
    # knot is a coil built from overlapping lobes offset left and right, so
    # its outline is lumpy rather than a smooth lozenge. Barbs are steep and
    # project well clear of the strand rather than splaying sideways.
    "<svg xmlns='http://www.w3.org/2000/svg' width='72' height='14'>"
    "<path fill='#000' d='M0 6.6 Q9 2.6 18 6.6 Q27 2.6 36 6.6 Q45 2.6 54 6.6"
    " Q63 2.6 72 6.6 L72 7.4 Q63 11.4 54 7.4 Q45 11.4 36 7.4 Q27 11.4 18 7.4"
    " Q9 11.4 0 7.4 Z'/>"
    "<g fill='#000'>"
    "<ellipse cx='36' cy='7' rx='3.4' ry='4'/>"
    "<circle cx='34.5' cy='3.5' r='2.1'/>"
    "<circle cx='37.7' cy='5.3' r='2.3'/>"
    "<circle cx='34.3' cy='8.8' r='2.3'/>"
    "<circle cx='37.5' cy='10.7' r='2'/>"
    "</g>"
    "<g fill='none' stroke='#000' stroke-width='1.8' stroke-linecap='round'>"
    "<path d='M34.4 5.4 L32.2 0.6'/>"
    "<path d='M37.6 5.4 L39.8 0.6'/>"
    "<path d='M34.4 8.6 L32.2 13.4'/>"
    "</g></svg>"
)

GRAIN_SVG = (
    "<svg xmlns='http://www.w3.org/2000/svg' width='260' height='260'>"
    "<filter id='n'><feTurbulence type='fractalNoise' baseFrequency='0.82' "
    "numOctaves='4' stitchTiles='stitch'/></filter>"
    "<rect width='100%' height='100%' filter='url(#n)'/></svg>"
)


def _wander(rnd, span, amp, notch, deep, step=(2.0, 5.5), base=0.0):
    """Offsets along an edge: slow drift plus fine jitter, rare deeper bites."""
    pts, t, drift = [], 0.0, 0.0
    while t < span:
        drift = max(-amp, min(amp, drift + rnd.uniform(-0.45, 0.45)))
        off = abs(drift * 0.55 + rnd.uniform(0, amp * 0.5))
        if rnd.random() < notch:
            off += amp * rnd.uniform(*deep)
        pts.append((round(t, 1), round(base + off, 1)))
        t += rnd.uniform(*step)
    pts.append((float(span), pts[-1][1]))
    return pts


def _rip(rnd, p0, p1, amp, bow=0.0, notch=0.12, deep=(0.8, 1.8)):
    """A ragged tear from p0 to p1.

    The baseline is a bowed curve, not a chord: a straight run with fuzz on it
    still reads as a cut. `bow` displaces the curve along the normal, positive
    meaning into the photo. The wander then rides on top of that.
    """
    (x0, y0), (x1, y1) = p0, p1
    dx, dy = x1 - x0, y1 - y0
    length = (dx * dx + dy * dy) ** 0.5
    nx, ny = -dy / length, dx / length
    if nx < 0:
        nx, ny = -nx, -ny
    cx, cy = (x0 + x1) / 2 + nx * bow, (y0 + y1) / 2 + ny * bow
    out, t, drift = [], 0.0, 0.0
    while t < length:
        drift = max(-amp, min(amp, drift + rnd.uniform(-0.7, 0.7)))
        off = abs(drift * 0.7 + rnd.uniform(0, amp * 0.6))
        if rnd.random() < notch:
            off += amp * rnd.uniform(*deep)
        f = t / length
        bx = (1 - f) ** 2 * x0 + 2 * (1 - f) * f * cx + f * f * x1
        by = (1 - f) ** 2 * y0 + 2 * (1 - f) * f * cy + f * f * y1
        out.append((round(bx + nx * off, 1), round(by + ny * off, 1)))
        t += rnd.uniform(1.4, 3.6)
    out.append((round(x1, 1), round(y1, 1)))
    return out


W, H = 400, 300                 # mask viewBox, stretched to fit each print
BOTTOM_INSET = 7.5              # baseline depth of the bottom rip


def _svg(d):
    return ("<svg xmlns='http://www.w3.org/2000/svg' width='%d' height='%d' "
            "viewBox='0 0 %d %d' preserveAspectRatio='none'>"
            "<path fill='#000' d='%s Z'/></svg>" % (W, H, W, H, " ".join(d)))


EDGES = ["top", "right", "bottom", "left"]
CORNER_BETWEEN = {"tr": ("top", "right"), "br": ("right", "bottom"),
                  "bl": ("bottom", "left"), "tl": ("left", "top")}


def _at(name, t, o=0.0):
    """A point on one edge: t along it clockwise, o pushed inward."""
    if name == "top":
        return (t, o)
    if name == "right":
        return (W - o, t)
    if name == "bottom":
        return (W - t, H - o)
    return (o, H - t)


def _span(name):
    return W if name in ("top", "bottom") else H


def _edge(rnd, name, torn, amp, notch, deep, base=0.0):
    """Points along one edge, walked clockwise, offsets pushed inward.

    Clockwise throughout: top left-to-right, right top-to-bottom, bottom
    right-to-left, left bottom-to-top. Walking one backwards makes the polygon
    cross itself, which shows as a slash across the image, not an edge.
    """
    span = _span(name)
    at = lambda t, o: _at(name, t, o)
    if not torn:
        return [(0.0, at(0.0, 0.0)), (span, at(span, 0.0))]
    return [(t, at(t, o)) for t, o in _wander(rnd, span, amp, notch, deep, base=base)]


def torn_edge_svg(seed=20260906, torn=("right", "bottom"), corner="bl",
                  cut=(50.0, 36.0), bow=-16.0):
    """Outline for a torn print.

    `torn` picks which edges are ragged; the rest are clean cuts. `corner` rips
    that corner away along a bowed diagonal, or None leaves every corner square.
    `cut` is how far back along each adjoining edge the rip starts.
    """
    rnd = random.Random(seed)

    pts = {}
    for name in EDGES:
        base = BOTTOM_INSET if name == "bottom" else 0.0
        # 9.0 on the bottom: the wander has to span the print margin, or the
        # rip sits wholly inside or wholly outside the photo's edge.
        amp = 9.0 if name == "bottom" else 2.4
        pts[name] = _edge(rnd, name, name in torn, amp,
                          0.018 if name == "bottom" else 0.05,
                          (0.3, 0.55) if name == "bottom" else (1.0, 1.8), base)

    rip = []
    if corner:
        before, after = CORNER_BETWEEN[corner]
        span_b = W if before in ("top", "bottom") else H
        keep_b = [p for p in pts[before] if p[0] <= span_b - cut[0]]
        keep_a = [p for p in pts[after] if p[0] >= cut[1]]
        assert keep_b and keep_a, "corner cut longer than the edges it joins"
        pts[before], pts[after] = keep_b, keep_a

        # A clean edge carries only its two endpoints, so truncation leaves the
        # far corner rather than a point at `cut`. Taking that as the rip's end
        # runs it right across the print. Compute both ends from the edge
        # parametrisation, and only prefer an actual point on a torn edge, so
        # the rip meets the tear it continues from.
        start = keep_b[-1][1] if len(keep_b) > 2 else _at(before, span_b - cut[0])
        end = keep_a[0][1] if len(keep_a) > 2 else _at(after, cut[1])
        assert min(end) >= -1 and end[0] <= W + 1 and end[1] <= H + 1, "rip end off-canvas"
        rip = _rip(rnd, start, end, 3.6, bow=bow, notch=0.05, deep=(0.4, 0.9))

    d, seen_rip = [], False
    for name in EDGES:
        for _, xy in pts[name]:
            d.append("L%s %s" % (round(xy[0], 1), round(xy[1], 1)))
        if corner and name == CORNER_BETWEEN[corner][0]:
            d += ["L%s %s" % (x, y) for x, y in rip]
            seen_rip = True
    assert not corner or seen_rip, "corner rip was never emitted"
    d[0] = "M" + d[0][1:]
    return _svg(d)






def _stains(seed, blotches=(5, 8), scuffs=(0, 2)):
    """A random scatter of blotches and scuffs, as a CSS background stack."""
    rnd = random.Random(seed)
    parts = []
    for _ in range(rnd.randint(*blotches)):
        parts.append(
            "radial-gradient(ellipse %d%% %d%% at %d%% %d%%, "
            "rgba(%d,%d,%d,%.2f), transparent %d%%)" % (
                rnd.randint(14, 50), rnd.randint(12, 44),
                rnd.randint(-6, 106), rnd.randint(-6, 106),
                rnd.randint(42, 92), rnd.randint(30, 64), rnd.randint(16, 40),
                # multiplied over an already dark, desaturated print, anything
                # under about 0.3 simply does not show
                rnd.uniform(0.34, 0.62), rnd.randint(58, 74)))
    for _ in range(rnd.randint(*scuffs)):
        at = rnd.uniform(18, 82)
        # Faint and soft-edged. A hard band at high opacity reads as a drawn
        # line rather than a crease in the paper.
        parts.append(
            "linear-gradient(%ddeg, transparent %.1f%%, rgba(66,48,30,%.2f) %.1f%%, "
            "transparent %.1f%%)" % (rnd.randint(64, 132), at - 4.0,
                                     rnd.uniform(0.07, 0.15), at, at + 4.0))
    return (",\n" + " " * 6).join(parts)


def _uri(svg):
    return 'url("data:image/svg+xml,%s")' % urllib.parse.quote(svg, safe="")


def build():
    """The generated block, markers included."""
    # Different edges, different corners, different counts: four sheets torn
    # by four different people, not one tear reused.
    tears = [
        ("booth", dict()),
        ("jars", dict(seed=8812, torn=("top", "right"), corner="tr",
                      cut=(64.0, 44.0), bow=-13.0)),
        ("sauces", dict(seed=3390, torn=("right", "bottom", "left"),
                        corner="br", cut=(38.0, 58.0), bow=-21.0)),
        ("story", dict(seed=5521, torn=("bottom", "left"), corner="tl",
                       cut=(54.0, 62.0), bow=-14.0)),
    ]
    lines = [OPEN, "  :root {",
             "    --grain: %s;" % _uri(GRAIN_SVG),
             "    --wire: %s;" % _uri(WIRE_SVG)]
    lines += ["    --tear-%s: %s;" % (n, _uri(torn_edge_svg(**kw)))
              for n, kw in tears]
    lines.append("")
    lines += ["    --stain-%s:\n      %s;" % (n, _stains(s)) for n, s in
              [("booth", 4102), ("jars", 7734), ("sauces", 2915), ("story", 6608)]]
    lines += ["  }", CLOSE]
    return "\n".join(lines)


def main():
    page = open(PAGE, encoding="utf-8").read()
    block = re.search(re.escape(OPEN) + ".*?" + re.escape(CLOSE), page, re.S)
    if not block:
        sys.exit("FAIL: %s has no generated block. Expected:\n%s\n...\n%s"
                 % (PAGE, OPEN, CLOSE))
    fresh = build()
    if "--check" in sys.argv:
        if block.group(0) != fresh:
            sys.exit("FAIL: %s is out of date. Run tools/make-assets.py" % PAGE)
        print("%s is up to date" % PAGE)
        return
    if block.group(0) == fresh:
        print("%s already up to date" % PAGE)
        return
    open(PAGE, "w", encoding="utf-8").write(page[:block.start()] + fresh
                                            + page[block.end():])
    print("rewrote the generated block in %s" % PAGE)


if __name__ == "__main__":
    main()
